### ISSUE TITLE
Are app-breaking trackers intentional?

### ISSUE THREAD

**Issue by HanabishiRecca** [Exodus-Privacy/etip#115]
Are app-breaking trackers intentional? E.g. this rule https://etip.exodus-privacy.eu.org/trackers/3146883e-985d-461c-91e2-e0eb9b12f91c/
Disabling `mozilla.components.lib.crash.handler.CrashHandlerService` in Firefox breaks the app.

**Comment by blaueente** [comment]
As far as I understand it, this database is only meant for *detecting* trackers by their class names, and does not make any other assumptions about that class, specifically not if the app relies on it for functionality.
How exactly did you disable that class?

**Comment by HanabishiRecca** [comment]
> How exactly did you disable that class?

This is actually doesn't matter. In any possible way: manually via `pm` command or `IFW` rule, or using software that deal with applications like `MyAndroidTools`, `AppManager` etc.

**Comment by jawz101** [comment]
I don't know how to reject a tracker but that ETIP entry doesn't seem appropriate for Exodus

**Comment by pnu-s** [comment]
@HanabishiRecca The ETIP database is an investigation platform (this is actually the IP in ETIP) therefore some of the trackers in it are not yet validated or reviewed.

If you want a more "mature" database, you can check directly https://github.com/Exodus-Privacy/exodus instead.


> I don't know how to reject a tracker but that ETIP entry doesn't seem appropriate for Exodus.

There is no way to do so unfortunately, that's why I would like to add at least a comment system on ETIP.

> and a crash reporter is not in my definition of a tracker

That depends on a lot of things in my opinion, for instance whether the app organization is the only one to receive the data.
But it seems to fit with this definition: https://reports.exodus-privacy.eu.org/en/info/trackers/
