### ISSUE TITLE
Separate field for sdk documentation

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/etip#19]
I was also wondering if we could have a separate field for url to the support documentation for sdk integration instructions since we all kinda throw them in either the short or long description field.  Perhaps sdk documentation/support url's warrant their own field?

_Originally posted by @jawz101 in https://github.com/Exodus-Privacy/etip/issues/11#issuecomment-472265850_

**Comment by simpnu** [comment]
@jawz101 I think we need to add this to a more general discussion about the format of trackers definition. We need to have this discussion with people like @seandiggity and trackers data contributors to make sure we agree on a shared format.

Maybe this repo is the right place to have this discussion, if we don't have a better idea.

**Comment by eighthave** [comment]
I think we definitely want a field for SDK docs, it should probably be a list entry, since occasionally, there are multiple relevant docs.  That might also get to the definition of what each "tracker" entry represents in ETIP.  Currently, it seems to losely represent a product, as defined by the company that makes it.  Good examples of that are the Facebook and Google entries.  Other potential definitions could be:
* one specific SDK
* one company or organization

If the "tracker" entry was defined as a specific SDK, then the docs entry could be a single URL.  I don't have a clear opinion on which would make the most sense.  I'm fine with keeping it like it is, or changing it.  It would be nice to have it clearly defined though.

**Comment by pnu-s** [comment]
I think in most cases the tracker is a specific SDK (and then I agree with you that the docs entry can be a single URL).

This being said, for more convenience, I think that this rule is not followed for every SDK.

If we need to add a string field for each tracker to get the SDK documentation, that can be done easily.
I think it makes sense, we could display it more easily on exodus too.

**Comment by eighthave** [comment]
I think there definitely should be a field for SDK documentation, either a string or a list.

**Comment by pnu-s** [comment]
AFAIK there is only the possibility to have a string here

Should we use comma separated list then?

e.g.
`http://link1.com,http://link2.com`

**Comment by eighthave** [comment]
A string field should be workable.  We can start with a single URL per-field.  I don't know off hand of a URL-safe way to make a list of URLs, probably space-separated.
